#!/bin/bash
echo "Enter a number: "
read n
original=$n
rev=0
while [ $n -gt 0 ]
do
rem=$((n%10))
rev=$((rev*10+rem))
n=$((n/10))
done
if[$original -eq $rev];
then
echo "Palindrome"
else
echo "Not Palindrome"
fi
